### ISSUE TITLE
Make site responsive 

### ISSUE THREAD

**Issue by fatimakay** [fatimakay/fatimakay.github.io#1]
I tried to make it as responsive as possible but the page still breaks on certain breakpoints. It would be helpful if someone can assist me in this.

**Comment by abitsalihu** [comment]
Hey @fatimakay, I would like to help with this issue, I see there are problems in all the other pages except the landing page.

**Comment by fatimakay** [comment]
> 

Hello Abit, I've assigned you to the issue.

**Comment by abitsalihu** [comment]
Alright I'll start working on this just a little bit later. :)
